FROM opensuse

ARG REQUIRED_ARGUMENT

# getting out sourcecode
##############################
RUN zypper in -y go go-doc && zypper in -y make

##############################

# installing corosync
##############################

##############################
