FROM ubuntu

ARG REQUIRED_ARGUMENT

# getting out sourcecode
##############################

##############################

# installing corosync
##############################

##############################
